# Generated by Django 4.2.7 on 2023-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachtStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='yachtPhoto',
            field=models.ImageField(default='media/default.jpg', upload_to=''),
        ),
    ]
