# Generated by Django 4.2.7 on 2023-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachtStore', '0002_yacht_yachtphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='yid',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='yachtPhoto',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
    ]
